In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)



df = pd.read_csv(
    "../data/kepler_exoplanet_classification.csv"
)
print(df.shape)
df.head()

(7586, 10)

,kepoi_name,koi_disposition,koi_period,koi_duration,koi_depth,koi_impact,koi_prad,koi_teq,koi_insol,koi_model_snr
0,K00752.01,CONFIRMED,9.488036,2.95750,615.8,0.146,2.26,793.0,93.59,35.8
1,K00752.02,CONFIRMED,54.418383,4.50700,874.8,0.586,2.83,443.0,9.11,25.8
2,K00754.01,FALSE POSITIVE,1.736952,2.40641,8079.2,1.276,33.46,1395.0,891.96,505.6
3,K00755.01,CONFIRMED,2.525592,1.65450,603.3,0.701,2.75,1406.0,926.16,40.9
4,K00756.01,CONFIRMED,11.094321,4.59450,1517.5,0.538,3.90,835.0,114.81,66.5

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7586 entries, 0 to 7585
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   kepoi_name       7586 non-null   str
 1   koi_disposition  7586 non-null   str
 2   koi_period       7586 non-null   float64
 3   koi_duration     7586 non-null   float64
 4   koi_depth        7327 non-null   float64
 5   koi_impact       7327 non-null   float64
 6   koi_prad         7327 non-null   float64
 7   koi_teq          7327 non-null   float64
 8   koi_insol        7367 non-null   float64
 9   koi_model_snr    7327 non-null   float64
dtypes: float64(8), str(2)
memory usage: 592.8 KB

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
koi_period,7586.0,51.655891,111.831884,0.241843,2.243126,8.080979,30.55289,1.071233e+03
koi_duration,7586.0,5.712879,6.825779,0.104600,2.474975,3.836305,6.27100,1.385400e+02
koi_depth,7327.0,29525.640794,91164.509271,0.800000,182.700000,501.400000,2319.00000,1.541400e+06
koi_impact,7327.0,0.756030,3.196172,0.000000,0.227000,0.586000,0.91700,1.008060e+02
koi_prad,7327.0,104.156288,3180.266619,0.080000,1.500000,2.620000,24.18000,2.003460e+05
koi_teq,7327.0,1154.390064,900.585687,92.000000,581.000000,933.000000,1482.00000,1.466700e+04
koi_insol,7367.0,9391.243767,178173.484284,0.020000,27.210000,180.550000,1151.57500,1.094755e+07
koi_model_snr,7327.0,318.587062,881.036417,0.000000,15.400000,30.500000,114.85000,9.054700e+03